# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- {name: 'BIO',  url: 'BIO'}
- {name: 'ANDY',       url: 'ANDY'}
- {name: 'MUSIC',            url: 'MUSIC'}
- {name: 'ARTWORK', url: 'MY-ARTWORK'}
- {name: 'DEFICIT',              url: 'DEFICIT'}
- {name: 'AQUA',            url: 'aqua.html'}
- {name: 'TERMS',            url: 'TERMS/'}
- {name: 'PRIVACY',            url: 'PRIVACY/'}
# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:management@serendippo.me'}
- {icon: 'twitter', link:    'https://twitter.com/Andrea98Schwarz'}
- {icon: 'facebook', link:   'https://www.facebook.com/cohenjoachim98/'}
- {icon: 'instagram', link:  'https://instagram.com/cohenjoachim/'}
# Customize site text
  #pagination:
  #next_page: 'Newer'
  #previous_page: 'Older'
